#!/bin/sh
export R_PACKAGE_NO_CONFIGURE_WARNING=1
echo "checking for OpenMP support..."

# Detect OS
OS=`uname -s`

if [ "$OS" = "Darwin" ]; then
  OPENMP_CFLAGS="-Xclang -fopenmp"
  OPENMP_LIBS="-lomp"
else
  OPENMP_CFLAGS="-fopenmp"
  OPENMP_LIBS="-fopenmp"
fi

# Output substitutions
cat <<EOF > src/Makevars
PKG_CFLAGS = $OPENMP_CFLAGS
PKG_LIBS = $OPENMP_LIBS
EOF
